version: "3"
services:
  postgres:
    container_name: slpbotdb
    hostname: slpbotdb
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: slpbotdb-admin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  slpbot:
    container_name: slpbot
    hostname: slpbot
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
